name: Deploy Project
on:
  pull_request:
    types:
      - closed
  # push:
  #   branches:
  #     - "main"
  #     - "dev-*"
  #     - "feat/**"
jobs:
  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps~node~modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:unit
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps~node~modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: dist-files
      #     path: dist
      # path: |
      #   dist
      #   package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # - name: Get build artifacts
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: dist-files
      - name: Deploy
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{}' \
          ${{ secrets.RENDER_DEPLOY_HOOK }}
